# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'UI_MAIN.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(859, 642)
        MainWindow.setMinimumSize(QSize(268, 167))
        MainWindow.setMaximumSize(QSize(16777215, 16777215))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.timeFrame = QFrame(self.centralwidget)
        self.timeFrame.setObjectName(u"timeFrame")
        self.timeFrame.setGeometry(QRect(180, 587, 161, 31))
        self.timeFrame.setFrameShape(QFrame.Box)
        self.timeFrame.setFrameShadow(QFrame.Raised)
        self.sec = QLabel(self.timeFrame)
        self.sec.setObjectName(u"sec")
        self.sec.setGeometry(QRect(72, 6, 81, 21))
        self.trans_time = QLabel(self.timeFrame)
        self.trans_time.setObjectName(u"trans_time")
        self.trans_time.setGeometry(QRect(8, 6, 61, 21))
        self.status_frame = QFrame(self.centralwidget)
        self.status_frame.setObjectName(u"status_frame")
        self.status_frame.setGeometry(QRect(10, 587, 161, 31))
        self.status_frame.setFrameShape(QFrame.Box)
        self.status_frame.setFrameShadow(QFrame.Raised)
        self.show_status = QLabel(self.status_frame)
        self.show_status.setObjectName(u"show_status")
        self.show_status.setGeometry(QRect(52, 6, 101, 20))
        self.status_lbl = QLabel(self.status_frame)
        self.status_lbl.setObjectName(u"status_lbl")
        self.status_lbl.setGeometry(QRect(8, 8, 41, 16))
        self.go_dev_page = QPushButton(self.centralwidget)
        self.go_dev_page.setObjectName(u"go_dev_page")
        self.go_dev_page.setGeometry(QRect(354, 587, 111, 31))
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(479, 595, 371, 16))
        self.progressBar.setValue(0)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 10, 841, 571))
        self.TAB_WEB = QWidget()
        self.TAB_WEB.setObjectName(u"TAB_WEB")
        self.log_browser = QTextBrowser(self.TAB_WEB)
        self.log_browser.setObjectName(u"log_browser")
        self.log_browser.setGeometry(QRect(8, 280, 821, 251))
        self.wholeFrame = QFrame(self.TAB_WEB)
        self.wholeFrame.setObjectName(u"wholeFrame")
        self.wholeFrame.setGeometry(QRect(7, 10, 821, 261))
        font = QFont()
        font.setBold(False)
        font.setWeight(50)
        self.wholeFrame.setFont(font)
        self.wholeFrame.setFrameShape(QFrame.Box)
        self.wholeFrame.setFrameShadow(QFrame.Raised)
        self.btnFrame = QFrame(self.wholeFrame)
        self.btnFrame.setObjectName(u"btnFrame")
        self.btnFrame.setGeometry(QRect(10, 10, 261, 241))
        self.btnFrame.setFrameShape(QFrame.Box)
        self.btnFrame.setFrameShadow(QFrame.Raised)
        self.show_ori_btn = QPushButton(self.btnFrame)
        self.show_ori_btn.setObjectName(u"show_ori_btn")
        self.show_ori_btn.setGeometry(QRect(99, 5, 71, 41))
        font1 = QFont()
        font1.setFamily(u"Consolas")
        font1.setPointSize(10)
        font1.setBold(False)
        font1.setWeight(50)
        self.show_ori_btn.setFont(font1)
        self.show_trans_btn = QPushButton(self.btnFrame)
        self.show_trans_btn.setObjectName(u"show_trans_btn")
        self.show_trans_btn.setGeometry(QRect(10, 5, 81, 41))
        self.show_trans_btn.setFont(font1)
        self.stop_trans_btn = QPushButton(self.btnFrame)
        self.stop_trans_btn.setObjectName(u"stop_trans_btn")
        self.stop_trans_btn.setGeometry(QRect(179, 5, 71, 41))
        self.stop_trans_btn.setFont(font1)
        self.isPrintBoth = QCheckBox(self.btnFrame)
        self.isPrintBoth.setObjectName(u"isPrintBoth")
        self.isPrintBoth.setGeometry(QRect(10, 51, 151, 23))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(False)
        font2.setWeight(50)
        self.isPrintBoth.setFont(font2)
        self.isAutoTrans = QCheckBox(self.btnFrame)
        self.isAutoTrans.setObjectName(u"isAutoTrans")
        self.isAutoTrans.setGeometry(QRect(10, 94, 211, 23))
        self.isAutoTrans.setFont(font2)
        self.isPrintLog = QCheckBox(self.btnFrame)
        self.isPrintLog.setObjectName(u"isPrintLog")
        self.isPrintLog.setGeometry(QRect(10, 118, 211, 23))
        self.isPrintLog.setFont(font2)
        self.isActivateSK = QCheckBox(self.btnFrame)
        self.isActivateSK.setObjectName(u"isActivateSK")
        self.isActivateSK.setGeometry(QRect(10, 141, 211, 23))
        self.isActivateSK.setFont(font2)
        self.isActivateFF = QCheckBox(self.btnFrame)
        self.isActivateFF.setObjectName(u"isActivateFF")
        self.isActivateFF.setGeometry(QRect(10, 165, 211, 23))
        self.isActivateFF.setFont(font2)
        self.isActivateRO = QCheckBox(self.btnFrame)
        self.isActivateRO.setObjectName(u"isActivateRO")
        self.isActivateRO.setGeometry(QRect(10, 188, 211, 23))
        self.isActivateRO.setFont(font2)
        self.isPrintFuri = QCheckBox(self.btnFrame)
        self.isPrintFuri.setObjectName(u"isPrintFuri")
        self.isPrintFuri.setGeometry(QRect(29, 71, 151, 23))
        self.isPrintFuri.setFont(font2)
        self.isTransImage = QCheckBox(self.btnFrame)
        self.isTransImage.setObjectName(u"isTransImage")
        self.isTransImage.setGeometry(QRect(10, 211, 211, 23))
        self.isTransImage.setFont(font2)
        self.fbFrame = QFrame(self.wholeFrame)
        self.fbFrame.setObjectName(u"fbFrame")
        self.fbFrame.setGeometry(QRect(280, 10, 531, 241))
        self.fbFrame.setFrameShape(QFrame.Box)
        self.fbFrame.setFrameShadow(QFrame.Raised)
        self.adviceContent = QTextEdit(self.fbFrame)
        self.adviceContent.setObjectName(u"adviceContent")
        self.adviceContent.setGeometry(QRect(37, 46, 491, 191))
        self.adviceSubject = QLineEdit(self.fbFrame)
        self.adviceSubject.setObjectName(u"adviceSubject")
        self.adviceSubject.setGeometry(QRect(37, 25, 491, 20))
        self.adviceLabel = QLabel(self.fbFrame)
        self.adviceLabel.setObjectName(u"adviceLabel")
        self.adviceLabel.setGeometry(QRect(5, 6, 151, 16))
        self.adviceSubmitBtn = QPushButton(self.fbFrame)
        self.adviceSubmitBtn.setObjectName(u"adviceSubmitBtn")
        self.adviceSubmitBtn.setGeometry(QRect(468, 3, 61, 21))
        self.adviceLabel_2 = QLabel(self.fbFrame)
        self.adviceLabel_2.setObjectName(u"adviceLabel_2")
        self.adviceLabel_2.setGeometry(QRect(5, 26, 31, 16))
        self.adviceLabel_3 = QLabel(self.fbFrame)
        self.adviceLabel_3.setObjectName(u"adviceLabel_3")
        self.adviceLabel_3.setGeometry(QRect(5, 45, 31, 16))
        self.tabWidget.addTab(self.TAB_WEB, "")
        self.TAB_FILE = QWidget()
        self.TAB_FILE.setObjectName(u"TAB_FILE")
        self.f_log_browser = QTextBrowser(self.TAB_FILE)
        self.f_log_browser.setObjectName(u"f_log_browser")
        self.f_log_browser.setGeometry(QRect(21, 322, 791, 211))
        self.file_select_btn = QPushButton(self.TAB_FILE)
        self.file_select_btn.setObjectName(u"file_select_btn")
        self.file_select_btn.setGeometry(QRect(564, 42, 81, 31))
        self.SelectedFileList = QListWidget(self.TAB_FILE)
        self.SelectedFileList.setObjectName(u"SelectedFileList")
        self.SelectedFileList.setGeometry(QRect(22, 42, 531, 221))
        self.SelectedFileList.setDragDropMode(QAbstractItemView.NoDragDrop)
        self.label_2 = QLabel(self.TAB_FILE)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(23, 22, 131, 16))
        self.frame = QFrame(self.TAB_FILE)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(564, 81, 251, 181))
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Raised)
        self.f_isPrintBoth = QCheckBox(self.frame)
        self.f_isPrintBoth.setObjectName(u"f_isPrintBoth")
        self.f_isPrintBoth.setGeometry(QRect(7, 7, 151, 23))
        self.f_isPrintBoth.setFont(font2)
        self.f_isActivateRO = QCheckBox(self.frame)
        self.f_isActivateRO.setObjectName(u"f_isActivateRO")
        self.f_isActivateRO.setGeometry(QRect(7, 68, 121, 23))
        self.f_isActivateRO.setFont(font2)
        self.f_isActivateFF = QCheckBox(self.frame)
        self.f_isActivateFF.setObjectName(u"f_isActivateFF")
        self.f_isActivateFF.setGeometry(QRect(7, 38, 131, 23))
        self.f_isActivateFF.setFont(font2)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(6, 124, 231, 51))
        self.f_isActive_F_Sound = QCheckBox(self.frame)
        self.f_isActive_F_Sound.setObjectName(u"f_isActive_F_Sound")
        self.f_isActive_F_Sound.setGeometry(QRect(7, 98, 231, 23))
        self.f_isActive_F_Sound.setFont(font2)
        self.select_all = QCheckBox(self.TAB_FILE)
        self.select_all.setObjectName(u"select_all")
        self.select_all.setGeometry(QRect(474, 22, 81, 20))
        self.select_all.setFont(font2)
        self.select_all.setChecked(True)
        self.transed_file_dir = QLineEdit(self.TAB_FILE)
        self.transed_file_dir.setObjectName(u"transed_file_dir")
        self.transed_file_dir.setGeometry(QRect(24, 293, 551, 20))
        self.transed_file_dir.setReadOnly(True)
        self.label_3 = QLabel(self.TAB_FILE)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(23, 272, 471, 21))
        self.select_file_dir_btn = QPushButton(self.TAB_FILE)
        self.select_file_dir_btn.setObjectName(u"select_file_dir_btn")
        self.select_file_dir_btn.setGeometry(QRect(594, 292, 75, 23))
        self.file_translate_btn = QPushButton(self.TAB_FILE)
        self.file_translate_btn.setObjectName(u"file_translate_btn")
        self.file_translate_btn.setGeometry(QRect(649, 42, 81, 31))
        self.file_translate_stop_btn = QPushButton(self.TAB_FILE)
        self.file_translate_stop_btn.setObjectName(u"file_translate_stop_btn")
        self.file_translate_stop_btn.setGeometry(QRect(735, 42, 81, 31))
        self.open_file_dir_btn = QPushButton(self.TAB_FILE)
        self.open_file_dir_btn.setObjectName(u"open_file_dir_btn")
        self.open_file_dir_btn.setGeometry(QRect(674, 293, 75, 23))
        self.clear_fileList_btn = QPushButton(self.TAB_FILE)
        self.clear_fileList_btn.setObjectName(u"clear_fileList_btn")
        self.clear_fileList_btn.setGeometry(QRect(364, 20, 101, 21))
        self.tabWidget.addTab(self.TAB_FILE, "")
        self.TAB_NOVEL = QWidget()
        self.TAB_NOVEL.setObjectName(u"TAB_NOVEL")
        self.novel_idx = QListWidget(self.TAB_NOVEL)
        self.novel_idx.setObjectName(u"novel_idx")
        self.novel_idx.setGeometry(QRect(4, 30, 241, 291))
        self.indexLabel = QLabel(self.TAB_NOVEL)
        self.indexLabel.setObjectName(u"indexLabel")
        self.indexLabel.setGeometry(QRect(2, 6, 51, 21))
        font3 = QFont()
        font3.setPointSize(10)
        self.indexLabel.setFont(font3)
        self.syosetuBrowser = QTextBrowser(self.TAB_NOVEL)
        self.syosetuBrowser.setObjectName(u"syosetuBrowser")
        self.syosetuBrowser.setGeometry(QRect(254, 53, 571, 431))
        self.syosetuBrowser.setFont(font3)
        self.frame_2 = QFrame(self.TAB_NOVEL)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(253, 491, 411, 41))
        self.frame_2.setFrameShape(QFrame.Box)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.fontSizeBox = QSpinBox(self.frame_2)
        self.fontSizeBox.setObjectName(u"fontSizeBox")
        self.fontSizeBox.setGeometry(QRect(350, 10, 51, 22))
        self.fontSizeBox.setFont(font3)
        self.fontSizeBox.setMinimum(1)
        self.fontSizeBox.setMaximum(200)
        self.fontSizeBox.setValue(10)
        self.label_7 = QLabel(self.frame_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(277, 5, 71, 31))
        self.label_7.setFont(font3)
        self.fontComboBox = QFontComboBox(self.frame_2)
        self.fontComboBox.setObjectName(u"fontComboBox")
        self.fontComboBox.setGeometry(QRect(51, 9, 211, 22))
        font4 = QFont()
        font4.setFamily(u"\ub098\ub214\uace0\ub515OTF")
        font4.setPointSize(10)
        self.fontComboBox.setFont(font4)
        self.label_8 = QLabel(self.frame_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(6, 5, 41, 31))
        self.label_8.setFont(font3)
        self.prevBtn = QPushButton(self.TAB_NOVEL)
        self.prevBtn.setObjectName(u"prevBtn")
        self.prevBtn.setGeometry(QRect(670, 491, 75, 41))
        self.prevBtn.setFont(font3)
        self.nextBtn = QPushButton(self.TAB_NOVEL)
        self.nextBtn.setObjectName(u"nextBtn")
        self.nextBtn.setGeometry(QRect(750, 491, 75, 41))
        self.nextBtn.setFont(font3)
        self.syosetuUrl = QLineEdit(self.TAB_NOVEL)
        self.syosetuUrl.setObjectName(u"syosetuUrl")
        self.syosetuUrl.setGeometry(QRect(320, 7, 441, 20))
        self.status_lbl_2 = QLabel(self.TAB_NOVEL)
        self.status_lbl_2.setObjectName(u"status_lbl_2")
        self.status_lbl_2.setGeometry(QRect(254, 8, 61, 16))
        self.status_lbl_2.setFont(font3)
        self.loadSyosetu = QPushButton(self.TAB_NOVEL)
        self.loadSyosetu.setObjectName(u"loadSyosetu")
        self.loadSyosetu.setGeometry(QRect(764, 6, 61, 23))
        self.frame_3 = QFrame(self.TAB_NOVEL)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(3, 322, 241, 211))
        self.frame_3.setFrameShape(QFrame.Box)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.n_isPrintBoth = QCheckBox(self.frame_3)
        self.n_isPrintBoth.setObjectName(u"n_isPrintBoth")
        self.n_isPrintBoth.setGeometry(QRect(5, 10, 151, 23))
        self.n_isPrintBoth.setFont(font2)
        self.n_isActivateRO = QCheckBox(self.frame_3)
        self.n_isActivateRO.setObjectName(u"n_isActivateRO")
        self.n_isActivateRO.setGeometry(QRect(5, 51, 121, 23))
        self.n_isActivateRO.setFont(font2)
        self.n_isActivateFF = QCheckBox(self.frame_3)
        self.n_isActivateFF.setObjectName(u"n_isActivateFF")
        self.n_isActivateFF.setGeometry(QRect(5, 31, 131, 23))
        self.n_isActivateFF.setFont(font2)
        self.label_6 = QLabel(self.frame_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(6, 78, 111, 121))
        self.novel_title = QLabel(self.TAB_NOVEL)
        self.novel_title.setObjectName(u"novel_title")
        self.novel_title.setGeometry(QRect(254, 29, 571, 21))
        self.novel_title.setFont(font3)
        self.tabWidget.addTab(self.TAB_NOVEL, "")
        self.TAB_NORMAL = QWidget()
        self.TAB_NORMAL.setObjectName(u"TAB_NORMAL")
        self.japaneseText = QTextEdit(self.TAB_NORMAL)
        self.japaneseText.setObjectName(u"japaneseText")
        self.japaneseText.setGeometry(QRect(9, 40, 361, 451))
        font5 = QFont()
        font5.setPointSize(13)
        self.japaneseText.setFont(font5)
        self.normalTransBtn = QPushButton(self.TAB_NORMAL)
        self.normalTransBtn.setObjectName(u"normalTransBtn")
        self.normalTransBtn.setGeometry(QRect(377, 217, 81, 41))
        self.label_4 = QLabel(self.TAB_NORMAL)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(8, 17, 56, 20))
        self.label_5 = QLabel(self.TAB_NORMAL)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(462, 17, 56, 20))
        self.koreanText = QTextBrowser(self.TAB_NORMAL)
        self.koreanText.setObjectName(u"koreanText")
        self.koreanText.setGeometry(QRect(464, 40, 361, 451))
        self.koreanText.setFont(font5)
        self.isLiveTrans = QCheckBox(self.TAB_NORMAL)
        self.isLiveTrans.setObjectName(u"isLiveTrans")
        self.isLiveTrans.setGeometry(QRect(10, 494, 181, 31))
        self.copyKtext = QPushButton(self.TAB_NORMAL)
        self.copyKtext.setObjectName(u"copyKtext")
        self.copyKtext.setGeometry(QRect(463, 497, 61, 21))
        self.tabWidget.addTab(self.TAB_NORMAL, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Ehnd \uc6f9 \ubc88\uc5ed", None))
        self.sec.setText("")
        self.trans_time.setText(QCoreApplication.translate("MainWindow", u"\ubc88\uc5ed \uc2dc\uac04:", None))
        self.show_status.setText("")
        self.status_lbl.setText(QCoreApplication.translate("MainWindow", u"\uc0c1\ud0dc: ", None))
        self.go_dev_page.setText(QCoreApplication.translate("MainWindow", u"\uc81c\uc791\uc790 \ud648\ud398\uc774\uc9c0", None))
        self.progressBar.setFormat(QCoreApplication.translate("MainWindow", u"%p%", None))
        self.show_ori_btn.setText(QCoreApplication.translate("MainWindow", u"\uc6d0\ubcf8 \ubcf4\uae30\n"
"Alt + o", None))
        self.show_trans_btn.setText(QCoreApplication.translate("MainWindow", u"\ubc88\uc5ed\ubcf8 \ubcf4\uae30\n"
"Alt + t", None))
        self.stop_trans_btn.setText(QCoreApplication.translate("MainWindow", u"\ubc88\uc5ed \uc911\uc9c0\n"
"Alt + s", None))
        self.isPrintBoth.setText(QCoreApplication.translate("MainWindow", u"\uc6d0\ubb38/\ubc88\uc5ed\ubb38 \ub3d9\uc2dc \ucd9c\ub825", None))
        self.isAutoTrans.setText(QCoreApplication.translate("MainWindow", u"\ud398\uc774\uc9c0 \ubc14\ub014 \ub54c\ub9c8\ub2e4 \uc790\ub3d9 \ubc88\uc5ed", None))
        self.isPrintLog.setText(QCoreApplication.translate("MainWindow", u"\ubc88\uc5ed \ub85c\uadf8 \ucd9c\ub825", None))
        self.isActivateSK.setText(QCoreApplication.translate("MainWindow", u"\ub2e8\ucd95\ud0a4 \ud65c\uc131\ud654", None))
        self.isActivateFF.setText(QCoreApplication.translate("MainWindow", u"\uac15\uc81c \ud544\ud130 \ud65c\uc131\ud654", None))
        self.isActivateRO.setText(QCoreApplication.translate("MainWindow", u"[\ud55c\uc790] \ud615\ud0dc \uc81c\uac70", None))
        self.isPrintFuri.setText(QCoreApplication.translate("MainWindow", u"\ud6c4\ub9ac\uac00\ub098 \ucd9c\ub825", None))
        self.isTransImage.setText(QCoreApplication.translate("MainWindow", u"\uc774\ubbf8\uc9c0 \ubc88\uc5ed \ud65c\uc131\ud654", None))
        self.adviceSubject.setText("")
        self.adviceLabel.setText(QCoreApplication.translate("MainWindow", u"# \uac74\uc758 \uc0ac\ud56d \ubc0f \uc624\ub958 \uc81c\ubcf4", None))
        self.adviceSubmitBtn.setText(QCoreApplication.translate("MainWindow", u"\uc81c\ucd9c\ud558\uae30", None))
        self.adviceLabel_2.setText(QCoreApplication.translate("MainWindow", u"\uc81c\ubaa9:", None))
        self.adviceLabel_3.setText(QCoreApplication.translate("MainWindow", u"\ub0b4\uc6a9:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TAB_WEB), QCoreApplication.translate("MainWindow", u"\uc6f9 \ubc88\uc5ed", None))
        self.file_select_btn.setText(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c \uc120\ud0dd", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\uc120\ud0dd\ud55c \ud30c\uc77c \ub9ac\uc2a4\ud2b8", None))
        self.f_isPrintBoth.setText(QCoreApplication.translate("MainWindow", u"\uc6d0\ubb38/\ubc88\uc5ed\ubb38 \ub3d9\uc2dc \ucd9c\ub825", None))
        self.f_isActivateRO.setText(QCoreApplication.translate("MainWindow", u"[\ud55c\uc790] \ud615\ud0dc \uc81c\uac70", None))
        self.f_isActivateFF.setText(QCoreApplication.translate("MainWindow", u"\uac15\uc81c \ud544\ud130 \ud65c\uc131\ud654", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\uc9c0\uc6d0 \ud655\uc7a5\uc790: TXT, DOCX, PPTX, XLSX,\n"
"                  CSV, PDF, JPG, PNG,\n"
"                  MP3, MP4", None))
        self.f_isActive_F_Sound.setText(QCoreApplication.translate("MainWindow", u"\uc74c\uc131 \ubc88\uc5ed \ubaa9\uc18c\ub9ac \uc5ec\uc131\uc73c\ub85c \ubc14\uafb8\uae30", None))
        self.select_all.setText(QCoreApplication.translate("MainWindow", u"\ubaa8\ub450 \uc120\ud0dd", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\ubc88\uc5ed\ub41c \ud30c\uc77c \uc800\uc7a5\ud560 \ud3f4\ub354 \uc704\uce58:  <span style=\" color:#ff0000;\">\ud30c\uc77c \ubc88\uc5ed \uc804\uc5d0 \ubc18\ub4dc\uc2dc \uc800\uc7a5\ud560 \ud3f4\ub354\ub97c \uc120\ud0dd\ud574\uc8fc\uc138\uc694! </span></p></body></html>", None))
        self.select_file_dir_btn.setText(QCoreApplication.translate("MainWindow", u"\ud3f4\ub354 \uc120\ud0dd", None))
        self.file_translate_btn.setText(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c \ubc88\uc5ed", None))
        self.file_translate_stop_btn.setText(QCoreApplication.translate("MainWindow", u"\ubc88\uc5ed \uc911\uc9c0", None))
        self.open_file_dir_btn.setText(QCoreApplication.translate("MainWindow", u"\ud3f4\ub354 \uc5f4\uae30", None))
        self.clear_fileList_btn.setText(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c \uc804\uccb4 \ube44\uc6b0\uae30", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TAB_FILE), QCoreApplication.translate("MainWindow", u"\ud30c\uc77c \ubc88\uc5ed", None))
        self.indexLabel.setText(QCoreApplication.translate("MainWindow", u"\ubaa9\ucc28", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\uae00\uc790 \ud06c\uae30:", None))
        self.fontComboBox.setCurrentText(QCoreApplication.translate("MainWindow", u"\ub098\ub214\uace0\ub515OTF", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\ud3f0\ud2b8:", None))
        self.prevBtn.setText(QCoreApplication.translate("MainWindow", u"\uc774\uc804\ud654\n"
"<-", None))
        self.nextBtn.setText(QCoreApplication.translate("MainWindow", u"\ub2e4\uc74c\ud654\n"
"->", None))
        self.status_lbl_2.setText(QCoreApplication.translate("MainWindow", u"\uc18c\uc124 \uc8fc\uc18c:", None))
        self.loadSyosetu.setText(QCoreApplication.translate("MainWindow", u"\ubd88\ub7ec\uc624\uae30", None))
        self.n_isPrintBoth.setText(QCoreApplication.translate("MainWindow", u"\uc6d0\ubb38/\ubc88\uc5ed\ubb38 \ub3d9\uc2dc \ucd9c\ub825", None))
        self.n_isActivateRO.setText(QCoreApplication.translate("MainWindow", u"[\ud55c\uc790] \ud615\ud0dc \uc81c\uac70", None))
        self.n_isActivateFF.setText(QCoreApplication.translate("MainWindow", u"\uac15\uc81c \ud544\ud130 \ud65c\uc131\ud654", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"# \ubc88\uc5ed \uc9c0\uc6d0 \uc0ac\uc774\ud2b8\n"
"syosetu.org\n"
"syosetu.com\n"
"kakuyomu.jp         \n"
"alphapolis.co.jp\n"
"pixiv.net\n"
"novelist.jp\n"
"estar.jp", None))
        self.novel_title.setText(QCoreApplication.translate("MainWindow", u"\uc81c\ubaa9: ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TAB_NOVEL), QCoreApplication.translate("MainWindow", u"\uc18c\uc124 \ubc88\uc5ed", None))
        self.normalTransBtn.setText(QCoreApplication.translate("MainWindow", u"\uc77c\ud55c \ubc88\uc5ed\n"
"->", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\uc77c\ubcf8\uc5b4", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\ud55c\uad6d\uc5b4", None))
        self.isLiveTrans.setText(QCoreApplication.translate("MainWindow", u"\uc2e4\uc2dc\uac04 \uc74c\uc131 \ubc88\uc5ed", None))
        self.copyKtext.setText(QCoreApplication.translate("MainWindow", u"\ubcf5\uc0ac \ud558\uae30", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TAB_NORMAL), QCoreApplication.translate("MainWindow", u"\uc77c\ubc18 \ubc88\uc5ed", None))
    # retranslateUi

